accum_iter: 1
batch_size: 256
dataset_dir: ../data/cryoem_blobs_uniform_2000_max
dataset_file: ../data/merged.csv
dataset_max_size: null
dataset_min_size: null
device: cuda
epochs: 2
lr: 0.002
model: MinkLoc3D
no_workers: 4
weight_decay: 1e-4
