accum_iter: 1
batch_size: 1
dataset_dir: ../data/blobs_full
dataset_file: ../data/train.csv
dataset_max_size: null
dataset_min_size: null
device: cuda
epochs: 2
lr: 0.001
model: MinkLoc3D
no_workers: 2
weight_decay: 1e-4
